# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fn_document"
  s.version = "0.9.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Colgate Clark", "Kyle Maxwell"]
  s.date = "2012-07-27"
  s.description = "This handles complex document creation from XML for the FASI AMS system."
  s.email = "nathancolgate@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "fn_document.gemspec",
    "lib/fn/block.rb",
    "lib/fn/document.rb",
    "lib/fn/migrate.xslt",
    "lib/fn/node/base.rb",
    "lib/fn/node/context.rb",
    "lib/fn/node/root.rb",
    "lib/fn/pdf/node/begin_document.rb",
    "lib/fn/pdf/node/begin_page_ext.rb",
    "lib/fn/pdf/node/create_textflow.rb",
    "lib/fn/pdf/node/end_page_ext.rb",
    "lib/fn/pdf/node/fit_image.rb",
    "lib/fn/pdf/node/fit_pdi_page.rb",
    "lib/fn/pdf/node/fit_textflow.rb",
    "lib/fn/pdf/node/invert.rb",
    "lib/fn/pdf/node/load_image.rb",
    "lib/fn/pdf/node/open_pdi.rb",
    "lib/fn/pdf/node/open_pdi_page.rb",
    "lib/fn/pdf/node/resume_page.rb",
    "lib/fn/pdf/node/set_parameter.rb",
    "lib/fn/pdf/node/watermark.rb",
    "lib/fn/pdf/struct.rb",
    "lib/fn/pdf/writer.rb",
    "lib/fn/resource.rb",
    "lib/fn/swf/node/break.rb",
    "lib/fn/swf/node/flash.rb",
    "lib/fn/swf/node/font.rb",
    "lib/fn/swf/node/frame.rb",
    "lib/fn/swf/node/hot_spot.rb",
    "lib/fn/swf/node/image.rb",
    "lib/fn/swf/node/page.rb",
    "lib/fn/swf/node/photo_block.rb",
    "lib/fn/swf/node/text.rb",
    "lib/fn/swf/struct.rb",
    "lib/fn/swf/writer.rb",
    "lib/fn/util.rb",
    "lib/fn/validation.rng",
    "lib/fn_document.rb",
    "test/assets/logo.jpg",
    "test/assets/pdf_background.pdf",
    "test/assets/pdf_background_2.pdf",
    "test/helper.rb",
    "test/nathans_test.rb",
    "test/test_fn_document.rb"
  ]
  s.homepage = "http://github.com/nathancolgate/fn_document"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Gem for reading/writing/printing fn documents"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxslt-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<libxslt-ruby>, [">= 0"])
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<libxslt-ruby>, [">= 0"])
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

